---
- name: Ensure refertest group is present.
  group:
    name: "{{ refertest_group }}"
    state: present

- name: Ensure refertest user is present.
  user:
    name: "{{ refertest_user }}"
    group: "{{ refertest_group }}"
    state: present

- name: Ensure refertest directory is present.
  file:
    path: "{{ refertest_dir }}"
    owner: "{{ refertest_user }}"
    group: "{{ refertest_group }}"
    mode: 0750
    state: directory

- name: Ensure resources directory is present.
  file:
    path: "{{ refertest_resources_dir }}"
    owner: "{{ refertest_user }}"
    group: "{{ refertest_group }}"
    mode: 0770
    state: directory

- name: Check war file is present.
  stat:
    path: "{{ refertest_dir }}/refertest.war"
  register: refertest_war

- include_tasks: mysql.yml
- include_tasks: package.yml
  when: refertest_package_url is defined and refertest_war.stat.exists == false
- include_tasks: tomcat.yml
