---
- name: Tomcat - Ensure Tomcat directory is present.
  file:
    path: "{{ refertest_tomcat_dir }}"
    state: directory

- name: Tomcat - Ensure war file is present into tomcat.
  copy:
    src: "{{ refertest_dir }}/refertest.war"
    dest: "{{ refertest_tomcat_dir }}/webapps/{{ refertest_context_path }}.war"
    remote_src: yes
    owner: 'tomcat'
    group: "{{ refertest_group }}"
    mode: 0550
  register: refertest_copy_result
  changed_when: refertest_copy_result.checksum != refertest_war.stat.checksum

- name: "Tomcat - Ensure war file is deployed ({{ refertest_mysql_connector }} as a signature)."
  stat:
    path: "{{ refertest_tomcat_dir }}/webapps/{{ refertest_context_path }}/WEB-INF/lib/{{ refertest_mysql_connector }}"
  register: refertest_deployed

- name: Tomcat - Ensure default ROOT do not interfer.
  file:
    path: "{{ refertest_tomcat_dir }}/webapps/{{ refertest_context_path }}"
    state: absent
  when: refertest_context_path == 'ROOT' and refertest_deployed.stat.exists == false

- name: Tomcat - Ensure context.xml is present.
  template:
    src: 'context.xml.j2'
    dest: "{{ refertest_tomcat_dir }}/conf/context.xml"
    owner: 'tomcat'
    group: 'tomcat'
    mode: 0755
  register: refertest_context_xml

- name: Tomcat - Restart if needed.
  service:
    name: tomcat
    state: restarted
  when: not refertest_deployed.stat.exists or refertest_context_xml.changed

- name: Tomcat - Ensure tomcat service is started.
  service:
    name: tomcat
    state: started
